export function wordCount(text){return(String(text).trim().match(/\b[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*\b/gu)||[]).length;}
export function sentenceCount(text){return(String(text).match(/[.!?]+(?:\s|$)/g)||[]).length;}
export function lexicalDiversity(text){const t=(String(text).toLowerCase().match(/\b[a-z]+(?:['’-][a-z]+)*\b/g)||[]).filter(x=>x.length>2);return t.length?new Set(t).size/t.length:0;}
export function gradeBuild(items,answers={}){const details=items.map((item)=>{const response=Array.isArray(answers[item.id])?answers[item.id].filter(Boolean):[];const correct=item.accepted.some((a)=>a.length===response.length&&a.every((id,i)=>id===response[i]));return{itemId:item.id,response,correct,accepted:item.accepted,explanation:item.explanation,grammar:item.grammar};});return{score:details.filter(x=>x.correct).length,maxScore:details.length,unanswered:details.filter(x=>x.response.length===0).length,details};}
function commonDiagnostics(text){const words=wordCount(text),sentences=sentenceCount(text),diversity=lexicalDiversity(text);return{words,sentences,diversity,longRuns:(String(text).match(/\b\w+(?:\s+\w+){28,}\b/g)||[]).length,repeated:/(\b\w+\b)(?:\s+\1){2,}/i.test(text)};}
function countMatchedGroups(text,groups=[]){const n=String(text).toLowerCase();return groups.filter((alts)=>alts.some((p)=>n.includes(String(p).toLowerCase()))).length;}
function hasSocialConventions(text){const n=String(text).toLowerCase();const greeting=/(^|\n)\s*(dear|hello|hi)\b/.test(n),polite=/\b(could|would|please|thank|appreciate|possible|wondering)\b/.test(n),closing=/\b(sincerely|best|regards|thank you|thanks)\b/.test(n);return{greeting,polite,closing,count:[greeting,polite,closing].filter(Boolean).length};}
function ngrams(text,n=6){const tokens=(String(text).toLowerCase().match(/\b[a-z]+(?:['’-][a-z]+)*\b/g)||[]);const out=[];for(let i=0;i<=tokens.length-n;i++)out.push(tokens.slice(i,i+n).join(' '));return out;}
export function stimulusOverlap(response,stimulus){const r=new Set(ngrams(response,6)),s=new Set(ngrams(stimulus,6));const shared=[...r].filter((g)=>s.has(g));return{sharedSixWordSpans:shared.slice(0,8),count:shared.length,flag:shared.length>=2};}
export function estimateEmailLocally(task,response){const common=commonDiagnostics(response),matchedGoals=countMatchedGroups(response,task.rubricHints?.purposeGroups||[]),conventions=hasSocialConventions(response);if(!common.words)return{score:0,source:'rule_zero',confidence:1,diagnostics:['No response was submitted.'],matchedGoals,metrics:{...common,conventions}};const diagnostics=[];if(matchedGoals<3)diagnostics.push(`${3-matchedGoals} communication goal(s) may be missing or not explicit.`);if(conventions.count<2)diagnostics.push('Consider clearer email conventions and polite request language.');if(common.sentences<4)diagnostics.push('The response has limited sentence-level development.');if(common.longRuns)diagnostics.push('One or more sentences may be difficult to follow because they are very long.');if(!diagnostics.length)diagnostics.push('All three communication goals appear to be represented in the response.');return{score:null,source:'local_analysis',confidence:null,matchedGoals,diagnostics,metrics:{...common,conventions},note:'Local analysis is diagnostic only; it does not produce a holistic 0–5 score.'};}
export function estimateDiscussionLocally(task,response){const common=commonDiagnostics(response),n=String(response).toLowerCase(),position=/\b(i (?:agree|disagree|believe|think|support|favor|would)|in my (?:view|opinion)|should|should not|shouldn't)\b/.test(n),support=/\b(because|since|for example|for instance|therefore|as a result|this means|one reason|although|however)\b/.test(n),topicHits=(task.keywords||[]).filter((w)=>n.includes(w.toLowerCase())).length,stimulus=[task.question,...task.students.map((s)=>s.post)].join(' '),overlap=stimulusOverlap(response,stimulus);if(!common.words)return{score:0,source:'rule_zero',confidence:1,diagnostics:['No response was submitted.'],metrics:{...common,position,support,topicHits,overlap}};const diagnostics=[];if(!position)diagnostics.push('Make your position explicit.');if(!support)diagnostics.push('Add a reason, example, contrast, or consequence.');if(topicHits<2)diagnostics.push('Connect the response more specifically to the professor’s question.');if(common.words<100)diagnostics.push('The public task guidance says an effective response should contain at least 100 words.');if(overlap.flag)diagnostics.push('Several six-word spans overlap with the prompt or peer posts; make sure the contribution is in your own words.');if(!diagnostics.length)diagnostics.push('The response contains a visible position and supporting development.');return{score:null,source:'local_analysis',confidence:null,diagnostics,metrics:{...common,position,support,topicHits,overlap},note:'Local analysis is diagnostic only; it does not produce a holistic 0–5 score.'};}
export function writingRubricPayload(taskType,task,response){return{taskType,task,response,scale:{min:0,max:5,primary:'holistic'},constraints:{doNotInventScaledScore:true,citeEvidenceSpans:true,verifyEvidenceAgainstResponse:true,checkPromptBorrowing:true,returnJsonOnly:true}};}
